### ISSUE TITLE
OkHttpClientUtils

### ISSUE THREAD

**Issue by ParfenovVS** [Tinder/Scarlet#10]
What about extensions and utils from sample?

`OkHttpClient.newWebSocketFactory(...)`

**Comment by xombified23** [comment]
I am getting this today:
`ERROR: Failed to resolve: com.github.tinder.scarlet:scarlet-websocket-okhttp:0.1.2`

**Comment by israelyago** [comment]
> I am getting this today:
> `ERROR: Failed to resolve: com.github.tinder.scarlet:scarlet-websocket-okhttp:0.1.2`

Worked for me:
implementation 'com.tinder.scarlet:websocket-okhttp:0.1.10'
