### ISSUE TITLE
dependency websocket-okhttp

### ISSUE THREAD

**Issue by mher92dev** [Tinder/Scarlet#102]
Steps to reproduce

try to use Gradle dependency

implementation 'com.tinder.scarlet:scarlet:0.1.9'
implementation 'com.tinder.scarlet:scarlet-websocket-okhttp:0.1.9'

expected result -> Build completed successfully
actual result -> ERROR: Failed to resolve: com.tinder.scarlet:scarlet-websocket-okhttp:0.1.9

**Comment by aaronhe42** [comment]
the package id is now `websocket-okhttp` in 0.1.9. so changing the dependency to `com.tinder.scarlet:websocket-okhttp:0.1.9`

**Comment by mher92dev** [comment]
@aaronhe42 Thank you for reply ! Suggested solution works for me
