### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jemshit** [Tinder/Scarlet#11]
Hi, thanks for the library. I have question regarding to how did you handle such state transition:
App Opened   -> App Sent to background  -> App came to foreground (all in a second)

Is it:
`connecting` -> `disconnecting` -> `connecting` ? Do you queue states or just **immediately** transition to next state by cancelling, or restarting okHttp calls?

**Comment by zhxnlai** [comment]
The AndroidLifecycle plugin debounces/throttles state transitions with [a fixed duration](https://github.com/Tinder/Scarlet/blob/master/scarlet-lifecycle-android/src/main/java/com/tinder/scarlet/lifecycle/android/AndroidLifecycle.kt#L13).

`connecting` -> `disconnecting` -> `connecting`,
if happening within 1 second, becomes 
`connecting`

**Comment by jemshit** [comment]
If it happens in 2 seconds, then it is
'connecting-disconnecting-connecting' i guess. So within that 2 seconds do
you create okhttp request and cancel it, then start new request?

**Comment by zhxnlai** [comment]
@jemshit That's right

**Comment by jemshit** [comment]
Thanks
