### ISSUE TITLE
Connection closing after about 5 mins

### ISSUE THREAD

**Issue by Nyanny** [Tinder/Scarlet#112]
My Issue might be connection with #109 or duplicate it.
I tried to delete AndroidLifecycle from configuration as was told in Issue #18. But my connection closing after 5 mins, always 5 mins. What can be the problem?

**Comment by Nyanny** [comment]
Did not know, that android has http turned off by the default

**Comment by iadcialim** [comment]
@Nyanny So does removing AndroidLifecycle make your connection alive even if the app is in background?

**Comment by radityagumay** [comment]
@iadcialim yes it would. however it might be be closed due to doze mode, or any constraints that OSs has
