### ISSUE TITLE
Scarlet in Java/Android

### ISSUE THREAD

**Issue by subzero10** [Tinder/Scarlet#12]
Hi, I'm having trouble integrating Scarlet into my Android app written in Java. Can you provide an example please (maybe put it in the Readme section along with the Kotlin example)?

**Comment by subzero10** [comment]
28 days and no response. I will just close this and thank you all for your help.

**Comment by mccccccmike** [comment]
Kotlin is one hundred percent interoperable with Java ,so you use Scarlet in your Java Project is totally fine.

**Comment by subzero10** [comment]
I understand that. But, I could not find a way to provide a `WebSocket.Factory` and a `MessageAdapter.Factory`. For Message Adapter, I want to use `Gson`.

```
Scarlet scarletInstance = new Scarlet.Builder()
                .webSocketFactory(<PROBLEM_HERE>)
                .addMessageAdapterFactory(<PROBLEM_HERE>)
                .build();
```

**Comment by mccccccmike** [comment]
In build.gradle(Module:app), add these lines of code to support Kotlin in your Java project
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
For WebSocket.Factory，you need to create a kotlin file named for example OkHttpClientProvider.kt, 
fun getOkHttpClient(client: OkHttpClient) =
        client.newWebSocketFactory("ws://test.asdfd.com:2346/")
and
Scarlet scarlet = new Scarlet.Builder()
                .webSocketFactory(OKHttpClientProviderKt.getOkHttpClient(client))
                .lifecycle(lifecycle)
                .addMessageAdapterFactory(new GsonMessageAdapter.Factory())
                .addStreamAdapterFactory(new RxJava2StreamAdapterFactory())
                .build();
we are done.

**Comment by subzero10** [comment]
Awesome. Thank you very much!

**Comment by vivekpanchal** [comment]
Hey, @subzero10  have you implemented scarlet in your application ??
can you please provide the link to your application so that I can refer to it?

**Comment by slott** [comment]
@vivekpanchal 

Try this

		webSocketInterface = new Scarlet.Builder()
				.webSocketFactory(OkHttpClientUtils.newWebSocketFactory(okClient, "ws://echo.websocket.org"))
				.addMessageAdapterFactory(new GsonMessageAdapter.Factory())
				.build().create(VivinoWebSocketInterface.class);;

And then setup the interface like so

public interface VivinoWebSocketInterface {
	@Send
	void subscribe(String message);

	@Receive
	Stream<String> observeTicker();
}


And observe like this

getWebSocketInterface().observeTicker().start(new Stream.Observer<String>() {
			@Override
			public void onNext(String receivedMessage) {
				Log.d(TAG, "onNext");

			}

			@Override
			public void onError(Throwable throwable) {
				Log.d(TAG, "onError");

			}

			@Override
			public void onComplete() {
				Log.d(TAG, "onComplete");

			}
		});

And send message like this

		getWebSocketInterface().subscribe("my message");

**Comment by vivekpanchal** [comment]
thanks, @slott  for this easy implementation.

**Comment by slott** [comment]
> thanks, @slott for this easy implementation.

I have it up and running with header authentication as well if that is something you need. It seems server errors aren't really relayed so you need to add breakpoints inside the lib to figure out whats going on.

**Comment by swdmnd** [comment]
> @vivekpanchal
> 
> Try this
> 
> ```
> 		webSocketInterface = new Scarlet.Builder()
> 				.webSocketFactory(OkHttpClientUtils.newWebSocketFactory(okClient, "ws://echo.websocket.org"))
> 				.addMessageAdapterFactory(new GsonMessageAdapter.Factory())
> 				.build().create(VivinoWebSocketInterface.class);;
> ```
> 
> And then setup the interface like so
> 
> ```
> public interface VivinoWebSocketInterface {
> 	@Send
> 	void subscribe(String message);
> 
> 	@Receive
> 	Stream<String> observeTicker();
> }
> ```
> 
> And observe like this
> 
> ```
> getWebSocketInterface().observeTicker().start(new Stream.Observer<String>() {
> 			@Override
> 			public void onNext(String receivedMessage) {
> 				Log.d(TAG, "onNext");
> 
> 			}
> 
> 			@Override
> 			public void onError(Throwable throwable) {
> 				Log.d(TAG, "onError");
> 
> 			}
> 
> 			@Override
> 			public void onComplete() {
> 				Log.d(TAG, "onComplete");
> 
> 			}
> 		});
> ```
> 
> And send message like this
> 
> ```
> 		getWebSocketInterface().subscribe("my message");
> ```

Thank you for the example.
Could you implement this code to subscribe to WebSocket Events?
