### ISSUE TITLE
Lifecycle compilation error

### ISSUE THREAD

**Issue by ParfenovVS** [Tinder/Scarlet#13]
```
com.android.builder.multidex.D8MainDexList$MainDexListException: 
com.android.tools.r8.errors.CompilationError: 
Program type already present: com.tinder.scarlet.lifecycle.android.BuildConfig
```

**Comment by aaronhe42** [comment]
Do you have another Gradle Android module shares the same package name with `com.tinder.scarlet.lifecycle.android`?

**Comment by ParfenovVS** [comment]
@aaronhe42 I've one module only. Scarlet dependencies (0.1.3): 
```
implementation "com.github.tinder.scarlet:scarlet:$scarletVersion"
implementation "com.github.tinder.scarlet:scarlet-websocket-okhttp:$scarletVersion"
implementation "com.github.tinder.scarlet:scarlet-message-adapter-gson:$scarletVersion"
implementation "com.github.tinder.scarlet:scarlet-stream-adapter-rxjava2:$scarletVersion"
implementation "com.github.tinder.scarlet:scarlet-lifecycle-android:$scarletVersion"
```

**Comment by ArturKnaus** [comment]
Have you found a solution yet ? Because I stumbled upon a similar (same?) problem

`Program type already present: com.tinder.scarlet.lifecycle.android.AndroidLifecycle`

**Comment by ParfenovVS** [comment]
@ArturKnaus nope... something wrong with lifecycle module...

**Comment by aaronhe42** [comment]
looks like we accidentally brought in an older version of the scarlet into scarlet-lifecycle-android module. we'll publish a new artifact early next week. sorry about that.

**Comment by aaronhe42** [comment]
just released [0.1.4](https://github.com/Tinder/Scarlet/releases/tag/0.1.4) to fix the issue

**Comment by aaaldo** [comment]
Hello, 
I have a similar issue with another component here : 

`Program type already present: com.google.protobuf.AbstractMessageLite
Message{kind=ERROR, text=Program type already present: com.google.protobuf.AbstractMessageLite, sources=[Unknown source file], tool name=Optional.of(D8)}`

Here's my build gradle : 
`     scarletVersion = '0.1.4'

    implementation "com.github.tinder.scarlet:scarlet:$scarletVersion"
    implementation "com.github.tinder.scarlet:scarlet-websocket-okhttp:$scarletVersion"
    implementation "com.github.tinder.scarlet:scarlet-message-adapter-gson:$scarletVersion"
    implementation "com.github.tinder.scarlet:scarlet-stream-adapter-rxjava2:$scarletVersion"
    implementation "com.github.tinder.scarlet:scarlet-lifecycle-android:$scarletVersion"
`

Any insights ?

**Comment by makarenkoanton** [comment]
Hello @aaronhe42 , I think that find the mistake in lifecycle module. Maybe change from `implementation project(':scarlet')` to `implementation project(':scarlet-core')` ?

**Comment by wintermoon9** [comment]
Having a similar problem. Getting `Error: Program type already present: com.tinder.scarlet.websocket.okhttp.OkHttpWebSocket
`

**Comment by aaronhe42** [comment]
@aaaldo Do you have mixed protobuf-java and protobuf-lite dependencies in your project?

@makarenkoanton the life cycle android is meant to be an extension to the Scarlet, so depends on `scarlet` feels appropriate here.

@wintermoon9 weird! do you mind sharing a small sample project?

**Comment by makarenkoanton** [comment]
@aaronhe42 ok, maybe error in something other. But lifecycle module implement some other modules but not use it. For example I save 1mb just exclude all modules, which I don't use, but lifecycle implement. 
 ```
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-message-adapter-builtin'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-message-adapter-jackson'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-message-adapter-moshi'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-message-adapter-protobuf'

        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-stream-adapter-builtin'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-stream-adapter-coroutines'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-stream-adapter-rxjava'

        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-mqtt'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-socketio-client'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-socketio-mockserver'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-sse-okhttp'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-stomp'
        exclude group: 'com.github.tinder.scarlet', module: 'scarlet-protocol-websocket-mockserver'
```

All work fine after this. And when use firebase-in-message and scarlet with lifecycle you have @aaaldo 's problem

**Comment by aaronhe42** [comment]
@makarenkoanton which version of Scarlet are you using? as of 0.1.8 or 0.1.9-SNAPSHOT, lifecyle-android only depends on a few things that are absolutely minimum,  the transitive dependency `scarlet` only brings in the builtin adapters

**Comment by makarenkoanton** [comment]
@aaronhe42 I use 0.2.4

**Comment by aaronhe42** [comment]
@makarenkoanton do you mind opening a separate issue with 0.2.x in the title?

**Comment by makarenkoanton** [comment]
@aaronhe42 Do you mean to open a new issue?

**Comment by aaronhe42** [comment]
@makarenkoanton yes thanks!

**Comment by makarenkoanton** [comment]
[Issue](https://github.com/Tinder/Scarlet/issues/88)
