### ISSUE TITLE
Question - MinSdk 'scarlet: lifecycle-android"

### ISSUE THREAD

**Issue by roger-picpay** [Tinder/Scarlet#130]
Hello everyone.

I liked the library and import that to my project.
However, my project has minSdk 16 and the artifact 'scarlet: lifecycle-android' has minSDK 19.

I clone the scarlet project and changed the minSdk from 19 to 16 on that  artifact, and all works fine. Is it possible down SDK to 16 in that artifact? 

Thanks. 😃

**Comment by aaronweihe** [comment]
Thanks for the request, and the testing. Unfortunately we dont have any plans to lower our min sdk. the adoption for 19 and 16 are extremely low. If you still would want to support those devices, feel free to fork the project, and build your own.
