### ISSUE TITLE
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'

### ISSUE THREAD

**Issue by Gouravdeep** [Tinder/Scarlet#132]
i am facing protocolException. please check following code:
**
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        method()
    }

    private fun method(){

        val client = OkHttpClient.Builder()
            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))

        client.addInterceptor(object : Interceptor {
            override fun intercept(chain: Interceptor.Chain): Response {
                val original: Request = chain.request()

                val request: Request = original.newBuilder()
                    .header("Upgrade", "websocket")
                    .header("Connection", "keep-alive")
                    .method(original.method, original.body)
                    .build()

                return chain.proceed(request)
            }
        })

        val scarletInstance = Scarlet.Builder()
            .webSocketFactory(client.build().newWebSocketFactory("http://192.168.43.23:4000"))
            .addMessageAdapterFactory(MoshiMessageAdapter.Factory())
            .addStreamAdapterFactory(CoroutinesStreamAdapterFactory())
            .build()

        val gdaxService = scarletInstance.create<GdaxService>()

        runBlocking {
            gdaxService.observeWebSocketEvent().consumeEach {

                if (it is WebSocket.Event.OnConnectionFailed){
                    Log.e("data",it.throwable.toString())
                }else if (it is WebSocket.Event.OnConnectionOpened<*>){
                    Log.e("data","connected")
                }

            }
        }

    }

    interface GdaxService {
        @Receive
        fun observeWebSocketEvent(): ReceiveChannel<WebSocket.Event>
    }

}
**
_implementation 'com.tinder.scarlet:scarlet:0.1.10'
    implementation 'com.tinder.scarlet:scarlet-core:0.1.10'
    implementation 'com.tinder.scarlet:message-adapter-moshi:0.1.10'
    implementation 'com.tinder.scarlet:websocket-okhttp:0.1.10'
    implementation 'com.tinder.scarlet:stream-adapter-coroutines:0.1.10'
    implementation("com.squareup.okhttp3:logging-interceptor:4.3.1")_

**Comment by aaronweihe** [comment]
> .webSocketFactory(client.build().newWebSocketFactory("http://192.168.43.23:4000"))

it looks like it is trying to connect to an http server

**Comment by aaronweihe** [comment]
closed this due to inactivity. feel free to re-open this when the issue comes back
