### ISSUE TITLE
Horrible documentation

### ISSUE THREAD

**Issue by P1NG2WIN** [Tinder/Scarlet#159]
Please improve your documentation. 

Main page has info only about main scarlet dependency but mentions `android-lifecycle`, `scarlet-websocket-okhttp` and other depencencies which have to look in the maven page.

Main page links to outdated medium article

Demo app has unclear package naming (echo, gdax, root). Moreover, the demo app is generally very confusing and uses a lot of external libraries not related to scarlet, It is well-written in the open pr which offers another demo app

Main page has example only with rxjava, without coroutines

**Comment by james04gr** [comment]
Totally agree

**Comment by chnouman** [comment]
no doubt

**Comment by Dakrain** [comment]
totally agree :) struggle to implement the library.

**Comment by aaronweihe** [comment]
I'd organize the folder structure to like 
```
message-adapters/
  moshi/
  jackson/
  protobuf/
steam-adapters/
  rxjava2/
  coroutine/
```
to make it more obvious what those different artifacts are. and add README to each directory accordingly.

the medium link is fixed.

is https://github.com/Tinder/Scarlet/pull/140 the "better" demo app you are referring to? if so, let's discuss there.

as for examples in corotuine, just created an issue https://github.com/Tinder/Scarlet/issues/163 to track

PRs are always welcome if you have specific pain points.
