### ISSUE TITLE
0.2.x: Dependences

### ISSUE THREAD

**Issue by SergeyZabiyakin** [Tinder/Scarlet#162]
Where can I find the necessary dependencies for the 0.2.x branch ????????????????????????????????????????????????????????????????????
it doesn't work : 
    implementation 'com.github.tinder.scarlet:scarlet:0.2.4'
    implementation 'com.github.tinder.scarlet:scarlet-protocol-websocket-okhttp:0.2.4'
    implementation "com.github.tinder.scarlet:scarlet-stream-adapter-rxjava2:0.2.4"
    implementation "com.github.tinder.scarlet:scarlet-message-adapter-moshi:0.2.4"

**Comment by aaronweihe** [comment]
have you added `jitpack.io` to your maven repo config?

**Comment by SergeyZabiyakin** [comment]
No (( 
Thank you so much for your reply
