### ISSUE TITLE
Hi,how to keep websocket connected when app enters background?

### ISSUE THREAD

**Issue by mccccccmike** [Tinder/Scarlet#18]
I hope it is not a dump question...

**Comment by mccccccmike** [comment]
Thanks advice

**Comment by ozombo** [comment]
@zhxnlai this is surprising to me too as well. How did you come to the decision of removing it tho? Was it trial and error?

**Comment by ozombo** [comment]
> @mccccccmike If you remove the `AndroidLifecycle` from your builder, the WebSocket connection will stay on forever. Is that the intended behavior?

The connection closes when this isn't removed even on the foreground but works fine when removed.

**Comment by SecretsNetwork** [comment]
@ozombo did you find any solution?
