### ISSUE TITLE
What the actual scarlet version?

### ISSUE THREAD

**Issue by ViHtarb** [Tinder/Scarlet#190]
Hi, help me please, what the latest and actual scarlet version and packages? Because i found at least two versions and packages:
    implementation "com.github.tinder.scarlet:scarlet:0.2.4"
    implementation "com.github.tinder.scarlet:scarlet-websocket-okhttp:0.2.4"
    implementation "com.github.tinder.scarlet:scarlet-message-adapter-gson:0.2.4"
    implementation "com.github.tinder.scarlet:scarlet-stream-adapter-coroutines:0.2.4"
    implementation "com.github.tinder.scarlet:scarlet-lifecycle-android:0.2.4"
and
    implementation "com.tinder.scarlet:scarlet:0.1.12"
    implementation "com.tinder.scarlet:websocket-okhttp:0.1.12"
    implementation "com.tinder.scarlet:message-adapter-gson:0.1.12"
    implementation "com.tinder.scarlet:stream-adapter-coroutines:0.1.12"
    implementation "com.tinder.scarlet:lifecycle-android:0.1.12"

**Comment by aaronweihe** [comment]
0.1.12 is the latest production version. 0.2.x is the experimental version opens up to a wider net of protocols
