### ISSUE TITLE
Use raw instead of escaped strings in tests for json adapters

### ISSUE THREAD

**Issue by VisheshVadhera** [Tinder/Scarlet#20]
We can ideally replace the following line 
```
val expectedString = "{\"name\":\"value\"}"
```

with this one:
```
val expectedString = """{"name":"value"}"""
```
by leveraging raw strings provided by Kotlin.

**Comment by zhxnlai** [comment]
Hi @VisheshVadhera, could you further elaborate the issue?

**Comment by VisheshVadhera** [comment]
@zhxnlai I just edited the description of the issue with an example. 

I believe instead of escaping the double quotes inside the string literal by using a backslash, we can ideally use raw string literals [(here)](https://kotlinlang.org/docs/reference/basic-types.html#string-literals) provided by Kotlin to make it look more idiomatic.

**Comment by zhxnlai** [comment]
@VisheshVadhera Good idea! Please contribute 😀
