### ISSUE TITLE
Library not accessible through gradle

### ISSUE THREAD

**Issue by krokyze** [Tinder/Scarlet#3]
Hi,

I'm trying to add the library trough gradle but I get:  Failed to resolve: com.tinder.scarlet:scarlet:0.1.0
Can't find the library using: https://search.maven.org/#search%7Cga%7C1%7Cscarlet

**Comment by zhxnlai** [comment]
@krokyze Thanks for reporting the issue. We are still in the progress of pushing it to Bintray. Stay tuned!

**Comment by zhxnlai** [comment]
@krokyze I am glad to let you know that Scarlet is now available via [Jitpack](https://jitpack.io/#tinder/scarlet/) while we are working on publishing it to Bintray
