### ISSUE TITLE
Typo in versioning

### ISSUE THREAD

**Issue by a-manumohan** [Tinder/Scarlet#40]
The latest version name is misspelt as **apha** instead of **alpha**. Also, it should be alpha5.
<img width="614" alt="screen shot 2018-11-05 at 7 43 28 pm" src="https://user-images.githubusercontent.com/443636/48008513-4ca0fa00-e133-11e8-9e83-d9c4aeea9b60.png">

**Comment by zhxnlai** [comment]
Thanks for your feedback! The typo is fixed in the latest release `0.2.4-alpha1`
