### ISSUE TITLE
Make APIs user-friendly

### ISSUE THREAD

**Issue by kitttn** [Tinder/Scarlet#43]
Hello. 
Can you please explain me, wtf is going on here?

```
val scarletBuilder = Scarlet.Configuration(
    streamAdapterFactories = listOf(CoroutinesStreamAdapterFactory()),
    debug = true
)

val protocol = object : Protocol {
    override fun createChannelFactory(): Channel.Factory = object : Channel.Factory {
        override fun create(listener: Channel.Listener, parent: Channel?): Channel? = parent
    }

    override fun createEventAdapterFactory(): ProtocolSpecificEventAdapter.Factory {
        TODO: fill this
    }
}

val scarlet = Scarlet(protocol, scarletBuilder)
```

Is this a new way to create a Scarlet instance, really?
If yes - where is documentation? Wtf is `ProtocolSpecificEventAdapter`? Why i need `ChannelFactory`?

**Comment by kitttn** [comment]
At least make a README example correct or point developers to version, for which that README was created for.

**Comment by zhxnlai** [comment]
Thank you for your feedback! @kitttn

I will update the main README soon but for now please refer to the README file on https://github.com/Tinder/Scarlet/tree/0.2.x

We made breaking API changes in the new version of Scarlet to support other protocols: Socket IO, SSE, MQTT, and STOMP. You might find it helpful to take a look at the example usages of all the protocols in the demo app: https://github.com/Tinder/Scarlet/tree/0.2.x/demo/src/main/java/com/tinder/app and test rules: https://github.com/Tinder/Scarlet/tree/0.2.x/scarlet-test-utils/src/main/java/com/tinder/scarlet/testutils/rule

**Comment by kitttn** [comment]
@zhxnlai sorry for negative emotions as well - i looked for examples everywhere except the 0.2.x branch. Thanks for pointing that out!
