### ISSUE TITLE
STOMP Compatibility

### ISSUE THREAD

**Issue by forresthopkinsa** [Tinder/Scarlet#5]
The standard for websocket communication is often regarded as being [STOMP](http://stomp.github.io/). Does this / will this library have STOMP compatibility in its message layer?

**Comment by zhxnlai** [comment]
It is possible to build a STOMP over WebSocket client using Scarlet. You will need to write message adapters for the classes that represent STOMP frames.

**Comment by forresthopkinsa** [comment]
Cool.

**Comment by alfredorueda** [comment]
Please, can you provide the URL of the demo app (Android client using STOMP)? There are a lot of resources at https://github.com/Tinder/Scarlet/tree/0.2.x
Thanks! ;-)

**Comment by alfredorueda** [comment]
> @forresthopkinsa
> We are working on it: https://github.com/Tinder/Scarlet/tree/0.2.x
> 
> Please check out the demo app and [tests](https://github.com/Tinder/Scarlet/blob/0.2.x/scarlet-protocol-stomp/src/test/java/com/tindre/scarlet/stomp/StompIntegrationTest.kt)

I would love to test the STOMP Android Demo App. Can you point to the exact URL, please?

**Comment by zhxnlai** [comment]
@alfredorueda Sorry, we only have [integration tests](https://github.com/Tinder/Scarlet/blob/0.2.x/scarlet-protocol-stomp/src/test/java/com/tindre/scarlet/stomp/StompIntegrationTest.kt) for STOMP. We don't have a demo for STOMP because we couldn't find a public STOMP server to connect to. You could checkout other demos and [here](https://github.com/Tinder/Scarlet/blob/0.2.x/scarlet-test-utils/src/main/java/com/tinder/scarlet/testutils/rule/GozirraStompConnection.kt#L99) for examples to use Scarlet to establish a STOMP connection

**Comment by spipau** [comment]
I tried and failed to implement a STOMP connection because of a lack of documentation. Please add a working example and not just the tests, even if you don't connect to a real server. I will now shift to another solution/library.

**Comment by forresthopkinsa** [comment]
@zhxnlai I work(ed) on possibly the most popular Android ws/STOMP library, and I've completely ceased supporting it, telling consumers to instead use Scarlet for their websocket needs. Tinder should be far better equipped to support the huge number of people needing to use WS in their apps.

Please document your library so that those people don't try to use your carefully architected code and end up hitting a dead end.

**Comment by amatsegor** [comment]
Aren't there any snapshot artifacts for protocol-stomp module?

**Comment by morozione** [comment]
Can you please provide an example of how to use the Scarlet as a stomp client? I've been looking for it for a couple of months but didn't get anything useful. Now I'm using another library in the prod for this but it works not well(
