### ISSUE TITLE
cannot access OkHttpWebSocket constructor and other errors

### ISSUE THREAD

**Issue by pooyakn** [Tinder/Scarlet#53]
Hi,
Using version 0.2.1-alpha4 I cannot compile sample code:
```kotlin
val protocol = OkHttpWebSocket(
            client,
            OkHttpWebSocket.SimpleRequestFactory(
                { Request.Builder().url("wss://ws-feed.gdax.com").build() },
                { ShutdownReason.GRACEFUL }
            )
        )
```

`OkHttpWebSocket` constructor is internal and it doesn't have a `SimpleRequestFactory` method, also constructor doesn't accept parameter types used in the sample.

Thanks.

**Comment by sbearben** [comment]
Please post your build.gradle

**Comment by pooyakn** [comment]
Here:

<code>
apply plugin: "com.android.application"
apply plugin: "kotlin-android"
apply plugin: "kotlin-android-extensions"
apply plugin: "kotlin-kapt"

android {
    def config = rootProject.extensions.getByName("ext")

    compileSdkVersion config["compile_sdk"]
    buildToolsVersion config["build_tools"]
    defaultConfig {
        applicationId config["application_id"]
        minSdkVersion config["min_sdk"]
        targetSdkVersion config["target_sdk"]
        versionCode config["version_code"]
        versionName config["version_name"]
        testInstrumentationRunner config["test_runner"]
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
        main.java.srcDirs += [file("$buildDir/generated/source/kapt/main")]
        test.java.srcDirs += "src/test/kotlin"
        androidTest.java.srcDirs += "src/androidTest/kotlin"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    def room_version = "2.1.0-alpha03"
    def scarlet_version = "0.2.1-alpha4"

    //Compile time dependencies
    kapt "androidx.lifecycle:lifecycle-compiler:2.1.0-alpha01"
    kapt "com.google.dagger:dagger-compiler:2.16"
    kapt "com.jakewharton:butterknife-compiler:9.0.0-rc3"
    kapt "androidx.room:room-compiler:$room_version"
    compileOnly "javax.annotation:jsr250-api:1.0"
    compileOnly "javax.inject:javax.inject:1"

    // Mutlidex support
    implementation "com.android.support:multidex:1.0.3"

    //Application dependencies
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version" // kotlin_version is 1.3.11
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.0"
    implementation "androidx.appcompat:appcompat:1.1.0-alpha01"
    implementation "androidx.constraintlayout:constraintlayout:2.0.0-alpha3"
    implementation "androidx.lifecycle:lifecycle-extensions:2.1.0-alpha01"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.1.0-alpha01"
    implementation "com.google.android.material:material:1.1.0-alpha02"
    implementation "androidx.annotation:annotation:1.0.1"
    implementation "com.google.dagger:dagger:2.16"
    implementation "com.squareup.retrofit2:converter-gson:2.3.0"
    implementation "com.squareup.okhttp3:logging-interceptor:3.11.0"
    implementation "com.google.android.material:material:1.1.0-alpha02"
    implementation "com.jakewharton:butterknife:9.0.0-rc3"
    implementation "androidx.room:room-runtime:$room_version"
    implementation "com.github.tinder.scarlet:scarlet:$scarlet_version"
    implementation "com.github.tinder.scarlet:scarlet-lifecycle-android:$scarlet_version"
    implementation "com.github.tinder.scarlet:scarlet-message-adapter-gson:$scarlet_version"
    implementation "com.github.tinder.scarlet:scarlet-stream-adapter-coroutines:$scarlet_version"
    implementation "com.github.tinder.scarlet:scarlet-protocol-websocket-okhttp:$scarlet_version"
    implementation "de.hdodenhof:circleimageview:2.2.0"

    //Unit/Integration tests dependencies
    testImplementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"
    testImplementation "org.robolectric:robolectric:3.8"
    testImplementation "junit:junit:4.12"
    testImplementation "com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0"
    testImplementation "org.amshove.kluent:kluent:1.14"
    testImplementation "androidx.room:room-testing:$room_version"

    //Acceptance tests dependencies
    androidTestImplementation "androidx.test:runner:1.1.1"
    androidTestImplementation "androidx.test:rules:1.1.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:3.1.1"
    androidTestImplementation "androidx.test.espresso:espresso-intents:3.1.1"
    androidTestImplementation "androidx.annotation:annotation:1.0.1"

    //Development dependencies
    debugImplementation "com.squareup.leakcanary:leakcanary-android:1.6.1"
    releaseImplementation "com.squareup.leakcanary:leakcanary-android-no-op:1.6.1"
    testImplementation "com.squareup.leakcanary:leakcanary-android-no-op:1.6.1"
}
<code>

**Comment by sbearben** [comment]
Same issue as #51

Try:

```
def scarlet_version = '0.2.1-alpha4'

dependencies {
    implementation "com.github.tinder.scarlet:scarlet:$scarlet_version"
    implementation "com.github.tinder.scarlet:scarlet-protocol-websocket-okhttp:$scarlet_version"
    implementation ("com.github.tinder.scarlet:scarlet-lifecycle-android:$scarlet_version") {
        exclude group: 'com.github.tinder', module: 'scarlet'
    }
    implementation "com.github.tinder.scarlet:scarlet-message-adapter-gson:0.2.1-alpha3"
    implementation "com.github.tinder.scarlet:scarlet-stream-adapter-coroutines:$scarlet_version"
}
```
