### ISSUE TITLE
Minimum sdk version for lifecycle-android

### ISSUE THREAD

**Issue by raylee4204** [Tinder/Scarlet#55]
Is there a reason why it's set to 19?

**Comment by aaronhe42** [comment]
not anything in particular,  probably because that's what Tinder app was.

**Comment by raylee4204** [comment]
Is there any way to bump it down to 15 or 16

On Jan 11, 2019 8:02 PM, "Aaron He" <notifications@github.com> wrote:

not anything in particular, probably because that's what Tinder app was.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tinder/Scarlet/issues/55#issuecomment-453704677>, or mute
the thread

**Comment by aaronhe42** [comment]
we dont plan to support 15/16 since the adoption is [really low](https://developer.android.com/about/dashboards/). if you do have a need, feel free to fork the library
