### ISSUE TITLE
ConnnectivityOnLifecycle does not close / re-open socket connection

### ISSUE THREAD

**Issue by raylee4204** [Tinder/Scarlet#56]
When using Scarlet with OkHttp websocket + AndroidLifecycle with `ofApplicationForeground in the configs, putting the app in the background and bringing back forward closes & re-initiates the connection. 

However, turning on/off the airplane mode does not close & re-initiate the socket connection.

**Comment by zhxnlai** [comment]
@raylee4204 What version of Scarlet are you using? `0.1.6` or `0.2.1-alpha5`?

**Comment by raylee4204** [comment]
State when turning on the airplane mode: StateTransition(fromState=com.tinder.scarlet.State$Connected, event=OnLifecycleStateChange(lifecycleState=com.tinder.scarlet.LifecycleState$Stopped), toState=Disconnecting(shouldRetry=true), sideEffect=com.tinder.scarlet.SideEffect$CloseProtocol)

**Comment by zhxnlai** [comment]
@raylee4204 Just released `0.2.2-alpha1` to address this issue. Would you let me know if works?

**Comment by raylee4204** [comment]
It doesn't seem like it's available on jitpack

**Comment by zhxnlai** [comment]
@raylee4204 Could you check out `0.2.2-alpha4` instead?

**Comment by raylee4204** [comment]
I will. Thanks

**Comment by raylee4204** [comment]
This still does not work.

**Comment by zhxnlai** [comment]
@raylee4204 I was not able to reproduce the behavior in the demo app. As you can see in the video attached, Iogs show up as expected when I turn airplane mode on and off. Could you help me reproduce it in the demo app?
[device-2019-01-21-225427.webm.zip](https://github.com/Tinder/Scarlet/files/2781610/device-2019-01-21-225427.webm.zip)

**Comment by raylee4204** [comment]
Confirmed it's working again. Thanks for your help!

**Comment by zhxnlai** [comment]
👍👍
