### ISSUE TITLE
How to add token in header ?

### ISSUE THREAD

**Issue by mhdtouban** [Tinder/Scarlet#6]
In retrofit, we can embed @HeaderMap and @FieldMap in case of POST or @QueryMap in case of GET. This way we can embed an authorized token in the header and pass by parameters either in GET or as a form in POST. My question, how can we achieve a similar thing in scarlet to pass by authorization token to the server?

**Comment by zhxnlai** [comment]
You can use an [interceptor](https://github.com/square/okhttp/wiki/Interceptors#rewriting-requests) to add headers to requests.
