### ISSUE TITLE
Connection reconnects constantly instead of sending ping

### ISSUE THREAD

**Issue by FrancoSabadini** [Tinder/Scarlet#70]
I've started using Scarlet this week and I've noticed that the WebSocket connection fails and a new one is started every minute or so. Is there an easy way to keep the connection open by sending a ping instead of re-connecting every time?

I'm using version 0.1.7.

**Comment by hantrungkien** [comment]
@FrancoSabadini do you mean Heartbeat?

**Comment by FrancoSabadini** [comment]
@hantrungkien yes, the ping-pong messages represent the heartbeat.

**Comment by hantrungkien** [comment]
@zhxnlai what do you think about this?

**Comment by hantrungkien** [comment]
@FrancoSabadini you can try my way

`
lateinit var pingDisposable: Disposable

scarlet.observeWebSocketEvent()
            .filter { it is WebSocketEvent.OnConnectionOpened }
           .doFinally {
                if (::pingDisposable.isInitialized && !pingDisposable.isDisposed) {
                    pingDisposable.dispose()
                }
            }
            .observeOn(Schedulers.io())
            .subscribe({
                scarlet.sendSubscribeLogin(rpc)

                Observable.interval(30, TimeUnit.SECONDS)
                    .map {
                         if (::pingDisposable.isInitialized && !pingDisposable.isDisposed) {
                    pingDisposable.dispose()
                         }
                pingDisposable = buildPingRequest(scarlet)
                    }
                    .subscribe()
            }, {
                Log.e(TAG, "observeWebSocketEvent: ERROR", it)
            })
`
`
fun buildPingRequest(): Disposable {
        return Observable.interval(30, TimeUnit.SECONDS)
            .map {
                val pingRequest = SystemServiceProto.PingRequest.newBuilder()
                    .setSendingTime(1)
                    .build()

                scarlet.pingSocket(build(pingRequest, Random().nextLong(), null))
            }
            .subscribe()
    }
`

**Comment by zhxnlai** [comment]
HI @FrancoSabadini, you can actually configure the ping interval in [OkHttpClient](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#pingInterval-java.time.Duration-). Would that solve the problem? 
```kotlin
private fun createOkHttpClient(): OkHttpClient {
    return okHttpClient.newBuilder()
        .pingInterval(PING_INTERVAL_SECONDS, TimeUnit.SECONDS)
        .build()
}
val scarlet = Scarlet.Builder()
    .webSocketFactory(
        createOkHttpClient().newWebSocketFactory(/* ... */)
    )
    .build()
```

**Comment by FrancoSabadini** [comment]
That worked perfectly @zhxnlai, Thanks for the help!

Thanks for the help also @hantrungkien, I think @zhxnlai is simpler for what I need so I'll go with that.

Do you guys think it's worth adding this to the Scarlet configuration to abstract it from OkHttp?

**Comment by zhxnlai** [comment]
@FrancoSabadini You're welcome!

> Do you guys think it's worth adding this to the Scarlet configuration to abstract it from OkHttp? (It might not be worth it as it's a low-level configuration though).

I agree that Scarlet configuration is not a good place to add it

**Comment by DysaniazzZ** [comment]
> HI @FrancoSabadini, you can actually configure the ping interval in [OkHttpClient](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#pingInterval-java.time.Duration-). Would that solve the problem?
> 
> ```kotlin
> private fun createOkHttpClient(): OkHttpClient {
>     return okHttpClient.newBuilder()
>         .pingInterval(PING_INTERVAL_SECONDS, TimeUnit.SECONDS)
>         .build()
> }
> val scarlet = Scarlet.Builder()
>     .webSocketFactory(
>         createOkHttpClient().newWebSocketFactory(/* ... */)
>     )
>     .build()
> ```

How to reset ping interval when WebSocket is connected?
