### ISSUE TITLE
Support for Kotlin Coroutines Flow - cold stream

### ISSUE THREAD

**Issue by gs-ts** [Tinder/Scarlet#77]
Any plans to support cold streams with Flow? 

https://github.com/Kotlin/kotlinx.coroutines/blob/master/CHANGES.md#version-130-m1
https://medium.com/@elizarov/cold-flows-hot-channels-d74769805f9

**Comment by a-manumohan** [comment]
Was looking for the same as any operations on ReceiveChannels are deprecated and flows are the way forward.

**Comment by a-manumohan** [comment]
I have created a PR for this https://github.com/Tinder/Scarlet/pull/116

**Comment by gs-ts** [comment]
resolved
